"use client";
import { useState } from "react";
import { generateContent, pollJob, createScheduledPost } from "@/lib/api";

const CONTENT_TYPES = [
  { value: "blog_post", label: "📝 Blog Post", desc: "SEO-optimized long-form content" },
  { value: "social_media", label: "📱 Social Media", desc: "Platform-ready posts with hashtags" },
  { value: "email", label: "💌 Email", desc: "Subject, preview & body copy" },
  { value: "ad_copy", label: "🎯 Ad Copy", desc: "Headlines and descriptions for ads" },
];
const TONES = ["Professional", "Playful", "Inspirational", "Educational", "Bold", "Conversational", "Luxury"];

export default function ContentPage() {
  const [form, setForm] = useState({
    topic: "",
    content_type: "blog_post",
    tone: "Professional",
    target_audience: "",
    keywords: "",
    word_count: 600,
  });
  const [status, setStatus] = useState<"idle" | "loading" | "done" | "error">("idle");
  const [progress, setProgress] = useState(0);
  const [content, setContent] = useState("");
  const [error, setError] = useState("");
  const [copied, setCopied] = useState(false);

  // Schedule Modal State
  const [showScheduleModal, setShowScheduleModal] = useState(false);
  const [scheduleTime, setScheduleTime] = useState("");
  const [schedulePlatform, setSchedulePlatform] = useState("Twitter/X");
  const [scheduleMsg, setScheduleMsg] = useState("");

  const handleGenerate = async () => {
    if (!form.topic.trim()) return;
    setStatus("loading");
    setProgress(0);
    setError("");
    setContent("");
    setScheduleMsg("");
    try {
      const payload = {
        topic: form.topic,
        content_type: form.content_type,
        tone: form.tone,
        target_audience: form.target_audience,
        keywords: form.keywords.split(",").map((k) => k.trim()).filter(Boolean),
        word_count: form.word_count,
      };
      const { job_id } = await generateContent(payload);
      const job = await pollJob(job_id, (j) => setProgress(Number(j.progress ?? 0)));
      const result = job.result as { content?: string };
      setContent(result?.content ?? "");
      setStatus("done");
    } catch (e: unknown) {
      setError((e as Error).message);
      setStatus("error");
    }
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(content);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  // Task 19: 1-Click Twitter/X Posting / Share
  const handleShareTwitter = () => {
    const tweetText = content.slice(0, 270) + (content.length > 270 ? "..." : "");
    const twitterUrl = `https://twitter.com/intent/tweet?text=${encodeURIComponent(tweetText)}`;
    window.open(twitterUrl, "_blank", "noopener,noreferrer");
  };

  // Task 20: PDF Export
  const handleExportPDF = () => {
    const printWindow = window.open("", "_blank");
    if (!printWindow) return;
    printWindow.document.write(`
      <!DOCTYPE html>
      <html>
        <head>
          <title>${form.topic || "AI Generated Content"}</title>
          <style>
            body { font-family: 'Segoe UI', Tahoma, sans-serif; padding: 40px; color: #1e293b; line-height: 1.6; }
            h1 { color: #4f46e5; border-bottom: 2px solid #e2e8f0; padding-bottom: 10px; }
            .meta { font-size: 13px; color: #64748b; margin-bottom: 25px; }
            .content { white-space: pre-wrap; font-size: 15px; background: #f8fafc; padding: 20px; border-radius: 8px; border: 1px solid #e2e8f0; }
            footer { margin-top: 40px; font-size: 12px; color: #94a3b8; text-align: center; }
          </style>
        </head>
        <body>
          <h1>${form.topic || "AI Generated Content"}</h1>
          <div class="meta">
            <strong>Type:</strong> ${form.content_type} | <strong>Tone:</strong> ${form.tone} | <strong>Date:</strong> ${new Date().toLocaleDateString()}
          </div>
          <div class="content">${content}</div>
          <footer>Generated by Autonomous Business Platform AI Studio</footer>
          <script>window.print();</script>
        </body>
      </html>
    `);
    printWindow.document.close();
  };

  // Task 21: Schedule Post
  const handleSaveSchedule = async () => {
    if (!content) return;
    try {
      await createScheduledPost({
        title: form.topic || "AI Generated Post",
        content: content,
        platform: schedulePlatform,
        scheduled_time: scheduleTime ? new Date(scheduleTime).toISOString() : new Date(Date.now() + 86400000).toISOString(),
      });
      setScheduleMsg("Post successfully scheduled! View under Workflows. 📅");
      setShowScheduleModal(false);
    } catch (err: unknown) {
      setError("Schedule failed: " + (err as Error).message);
    }
  };

  const selectedType = CONTENT_TYPES.find((t) => t.value === form.content_type);

  return (
    <div className="space-y-6 animate-fade-in max-w-6xl">
      <div>
        <h2 className="gradient-text text-2xl font-bold" style={{ letterSpacing: "-0.03em" }}>
          📝 AI Content Studio
        </h2>
        <p className="text-slate-500 text-sm mt-1">Generate blog posts, social media copy, and export directly to PDF or Twitter/X</p>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Form Controls */}
        <div className="lg:col-span-1 glass-card p-5 space-y-4">
          <h3 className="text-sm font-semibold text-slate-400 uppercase tracking-wider">Content Parameters</h3>

          <div>
            <label className="text-xs text-slate-400 mb-1 block">Content Format</label>
            <div className="grid grid-cols-2 gap-2">
              {CONTENT_TYPES.map((t) => (
                <button
                  key={t.value}
                  type="button"
                  onClick={() => setForm((f) => ({ ...f, content_type: t.value }))}
                  className={`p-2.5 rounded-lg border text-left transition-all ${
                    form.content_type === t.value
                      ? "bg-indigo-600/30 border-indigo-500 text-slate-100"
                      : "bg-white/5 border-white/10 text-slate-400 hover:border-slate-500"
                  }`}
                >
                  <div className="text-xs font-semibold">{t.label}</div>
                  <div className="text-[10px] text-slate-500 line-clamp-1">{t.desc}</div>
                </button>
              ))}
            </div>
          </div>

          <div>
            <label className="text-xs text-slate-400 mb-1 block">Topic / Title *</label>
            <textarea
              className="input-field"
              rows={3}
              placeholder="e.g., 5 Proven Strategies to Scale E-Commerce Stores in 2026"
              value={form.topic}
              onChange={(e) => setForm((f) => ({ ...f, topic: e.target.value }))}
            />
          </div>

          <div className="grid grid-cols-2 gap-3">
            <div>
              <label className="text-xs text-slate-400 mb-1 block">Tone</label>
              <select
                className="input-field"
                value={form.tone}
                onChange={(e) => setForm((f) => ({ ...f, tone: e.target.value }))}
              >
                {TONES.map((t) => <option key={t} value={t}>{t}</option>)}
              </select>
            </div>
            <div>
              <label className="text-xs text-slate-400 mb-1 block">Length (Words)</label>
              <input
                type="number"
                className="input-field"
                value={form.word_count}
                onChange={(e) => setForm((f) => ({ ...f, word_count: Number(e.target.value) }))}
              />
            </div>
          </div>

          <div>
            <label className="text-xs text-slate-400 mb-1 block">SEO Keywords (comma separated)</label>
            <input
              type="text"
              className="input-field"
              placeholder="ecommerce, scaling, AI tools"
              value={form.keywords}
              onChange={(e) => setForm((f) => ({ ...f, keywords: e.target.value }))}
            />
          </div>

          <button
            className="btn-primary w-full justify-center py-2.5"
            onClick={handleGenerate}
            disabled={status === "loading" || !form.topic.trim()}
          >
            {status === "loading" ? `⏳ Writing Content ${progress}%` : "⚡ Generate Content"}
          </button>

          {scheduleMsg && <div className="text-xs text-emerald-400 bg-emerald-500/10 p-3 rounded border border-emerald-500/20">{scheduleMsg}</div>}
          {error && <div className="text-xs text-rose-400 bg-rose-500/10 p-3 rounded border border-rose-500/20">{error}</div>}
        </div>

        {/* Content Output & Wow Features */}
        <div className="lg:col-span-2 space-y-4">
          {status === "loading" && (
            <div className="glass-card p-6 space-y-4">
              <h3 className="text-sm font-semibold text-slate-300">🤖 AI Crafting {selectedType?.label}...</h3>
              <div className="progress-bar">
                <div className="progress-fill" style={{ width: `${progress}%` }} />
              </div>
              <div className="space-y-3">
                <div className="skeleton h-12 rounded-xl" />
                <div className="skeleton h-32 rounded-xl" />
              </div>
            </div>
          )}

          {status === "idle" && (
            <div className="glass-card p-12 text-center h-full flex flex-col items-center justify-center space-y-2">
              <span className="text-6xl mb-2">📝</span>
              <div className="text-slate-300 font-semibold">Your AI Generated Article Will Appear Here</div>
              <p className="text-xs text-slate-500">Fill in your topic on the left and click "Generate Content".</p>
            </div>
          )}

          {status === "done" && content && (
            <div className="glass-card p-5 space-y-4">
              <div className="flex flex-wrap items-center justify-between gap-2 border-b border-white/5 pb-3">
                <h3 className="text-sm font-semibold text-slate-200 flex items-center gap-2">
                  <span>{selectedType?.label}</span> Output
                </h3>

                {/* Task 19 & Task 20 Action Bar */}
                <div className="flex flex-wrap items-center gap-2">
                  <button onClick={handleCopy} className="btn-secondary text-xs px-3 py-1.5">
                    {copied ? "✅ Copied" : "📋 Copy"}
                  </button>
                  <button onClick={handleShareTwitter} className="btn-primary text-xs px-3 py-1.5 bg-blue-500 hover:bg-blue-600">
                    🐦 Share on Twitter/X
                  </button>
                  <button onClick={handleExportPDF} className="btn-secondary text-xs px-3 py-1.5 text-indigo-300 border-indigo-500/30">
                    📄 Export as PDF
                  </button>
                  <button onClick={() => setShowScheduleModal(true)} className="btn-primary text-xs px-3 py-1.5 bg-emerald-600 hover:bg-emerald-700">
                    📅 Schedule Post
                  </button>
                </div>
              </div>

              <div className="bg-black/30 p-5 rounded-lg border border-white/5 text-sm text-slate-200 whitespace-pre-wrap leading-relaxed">
                {content}
              </div>
            </div>
          )}
        </div>
      </div>

      {/* Task 21: Schedule Modal */}
      {showScheduleModal && (
        <div className="fixed inset-0 z-50 bg-black/70 backdrop-blur-sm flex items-center justify-center p-4">
          <div className="glass-card p-6 max-w-md w-full space-y-4 animate-scale-up border-indigo-500/30">
            <div className="flex items-center justify-between">
              <h3 className="font-bold text-slate-100 text-lg">📅 Schedule Post</h3>
              <button onClick={() => setShowScheduleModal(false)} className="text-slate-400 hover:text-white">✕</button>
            </div>

            <div>
              <label className="text-xs text-slate-400 mb-1 block">Target Platform</label>
              <select
                className="input-field"
                value={schedulePlatform}
                onChange={(e) => setSchedulePlatform(e.target.value)}
              >
                <option value="Twitter/X">Twitter/X</option>
                <option value="LinkedIn">LinkedIn</option>
                <option value="Instagram">Instagram</option>
                <option value="Facebook">Facebook</option>
              </select>
            </div>

            <div>
              <label className="text-xs text-slate-400 mb-1 block">Publish Date & Time</label>
              <input
                type="datetime-local"
                className="input-field"
                value={scheduleTime}
                onChange={(e) => setScheduleTime(e.target.value)}
              />
            </div>

            <div className="flex items-center justify-end gap-3 pt-2">
              <button onClick={() => setShowScheduleModal(false)} className="btn-secondary text-xs">Cancel</button>
              <button onClick={handleSaveSchedule} className="btn-primary text-xs bg-emerald-600 hover:bg-emerald-700">
                Confirm Schedule 📅
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
